import 'package:flutter/material.dart'; // Where flutter finds what makes the app
import 'package:tech_120_app/Middleware/current_user.dart';
import 'package:tech_120_app/Views/Manual/home_page_view.dart'; // and home page
import 'package:tech_120_app/Views/Manual/Testing/chat_view.dart';
import 'package:tech_120_app/Views/bottom_tabs.dart';
import 'package:tech_120_app/Views/Manual/Mentor/mentor_profile.dart';
import 'package:tech_120_app/Views/Manual/login_placeholder.dart';
// Generated by: https://www.figma.com/community/plugin/842128343887142055/

void main() async {
  // Ensure Flutter binding initialized for async work (plugins, SharedPreferences)
  WidgetsFlutterBinding.ensureInitialized();

  // Try to initialize the current user from stored token before launching UI.
  final loaded = await initializeCurrentUser();

  // Starts the execution of the app
  runApp(FigmaToCodeApp(showLoginIfNotLoaded: !loaded));
  print("App Started. Current user loaded: $loaded");
}

class FigmaToCodeApp extends StatelessWidget {
  final bool showLoginIfNotLoaded;

  const FigmaToCodeApp({
    super.key,
    this.showLoginIfNotLoaded = false,
  }); // Complicated, hopefully no touch

  @override
  Widget build(BuildContext context) {
    final Widget homeWidget =
        (showLoginIfNotLoaded && currentUserStore.user == null)
        ? const LoginPlaceholder()
        : const BottomTabs();

    return MaterialApp(
      // The base of the app
      theme: ThemeData.light().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(
          255,
          0,
          0,
          0,
        ), // Background color
        appBarTheme: const AppBarTheme(
          backgroundColor: Color.fromARGB(
            255,
            64,
            128,
            196,
          ), // Color for the top bar
        ),
      ),
      home: homeWidget, // Load either login placeholder or bottom-tabs
      // Named routes used by `Navigator.pushNamed` in several views
      routes: {
        '/home': (context) => const HomePageView(),
        '/chat': (context) => const ChatView(),
        '/profile': (context) => const Placeholder(),
      },
    ); // ctrl + click to view
  }
}
