import 'package:flutter/material.dart'; // Where flutter finds what makes the app
import 'package:tech_120_app/Views/Manual/home_page_view.dart'; // and home page
import 'package:tech_120_app/Views/Manual/chat_view.dart';
import 'package:tech_120_app/Views/bottom_tabs.dart';
import 'package:tech_120_app/Views/Manual/Mentor/mentor_profile.dart';
// Generated by: https://www.figma.com/community/plugin/842128343887142055/

void main() {
  // Starts the execution of the app, no touch
  runApp(const FigmaToCodeApp());
  print("App Started");
}

class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key}); // Complicated, hopefully no touch

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      // The base of the app
      theme: ThemeData.light().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(
          255,
          0,
          0,
          0,
        ), // Background color
        appBarTheme: const AppBarTheme(
          backgroundColor: Color.fromARGB(
            255,
            64,
            128,
            196,
          ), // Color for the top bar
        ),
      ),
      home:
          const BottomTabs(), // Load the bottom-tabs root with separate stacks
      // Named routes used by `Navigator.pushNamed` in several views
      routes: {
        '/home': (context) => const HomePageView(),
        '/chat': (context) => const ChatView(),
        '/profile': (context) => const MentorMessagingView(),
      },
    ); // ctrl + click to view
  }
}
